### ISSUE TITLE
Profile processing error

### ISSUE THREAD

**Issue by tahereT** [jump-cellpainting/neurips-cpjump1#5]
I tried to run "Profile processing with pycytominer"'s commands but when I run

>  ./run.sh

this error raised:
![Screenshot from 2021-07-09 12-55-52](https://user-images.githubusercontent.com/18726258/125048327-0acf6b00-e0b5-11eb-8851-3ced03b08831.png)

and also I can't open profile's file:
![Screenshot from 2021-07-09 12-34-58](https://user-images.githubusercontent.com/18726258/125045436-3c930280-e0b2-11eb-9e06-90a3054dcd87.png)

could anyone help me with this error?

**Comment by niranjchandrasekaran** [comment]
Hi @tahereT, thanks for pointing this out. Can you run `git lfs pull` before you run `./run.sh`? I believe the `.gz` files which are in lfs have not downloaded when you clone the repo. Do let me know if this works and I will add this to the README as well.

**Comment by tahereT** [comment]
Hi @niranjchandrasekaran
Thanks for your answer. It works for me :))
